import javax.swing.JOptionPane;

public class Actualizar extends javax.swing.JPanel {

    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        buttonGroupOrientacion = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(22, 124, 214));
        jLabel1.setText("Para agregar una promesa presiona Enter");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel2.setBackground(new java.awt.Color(22, 22, 22));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre candidato:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jTextField1.setBackground(new java.awt.Color(229, 229, 229));
        jTextField1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(75, 75, 75));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 280, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, 10));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Cedula candidato:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(28, 30, 65));
        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(131, 190, 242));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una orientación politica para ver las opciones" }));
        jComboBox1.setBorder(null);
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 520, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ciudad:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        buttonGroupOrientacion.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(22, 124, 214));
        jRadioButton1.setText("Izquierda");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));
        buttonGroupOrientacion.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(22, 124, 214));
        jRadioButton2.setText("Derecha");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Orientacion Politica:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(28, 30, 65));
        jComboBox2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 255, 102));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(Principal.ObtenerCedulas()));
        jComboBox2.setBorder(null);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 310, -1));

        jTextArea1.setBackground(new java.awt.Color(28, 30, 65));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 255, 102));
        jTextArea1.setRows(1);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 460, 110));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Partido Politico:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("(Cada renglon seria una promesa)");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Ingrese la lista de promesas:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("->");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 20, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("->");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 20, 30));

        jButton1.setBackground(new java.awt.Color(22, 124, 214));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(229, 229, 229));
        jButton1.setText("Actualizar Candidato");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, -1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(22, 124, 214));
        jLabel7.setText("Actualizar Candidato existente");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(28, 30, 65));
        jComboBox3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(131, 190, 242));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cali", "Palmira", "Candelaria", "Dagua", "ElCerrito", "Florida", "Jamundi", "LaCumbre", "Pradera", "Vijes", "Yumbo", "tulua", "buga" }));
        jComboBox3.setBorder(null);
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>                        
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {   
        String cedula = (String) jComboBox2.getSelectedItem();
        Candidatos candidato = Candidatos.buscarCandidatosPorCedula(Principal.candidatos, cedula);
        if (candidato != null){
            String nombre = candidato.getNombre();
            String ciudad = candidato.getCiudad_origen();
            Boolean orientacion = candidato.getOrientacion_politica();
            String partido = candidato.getPartido_politico();
            String promesas = candidato.getLista_promesas();

            jTextField1.setText(nombre);
            jComboBox3.setSelectedItem(ciudad);
            if (orientacion){
                jRadioButton2ActionPerformed(evt);
                jRadioButton2.setSelected(true);
            }else{
                jRadioButton1ActionPerformed(evt);
                jRadioButton1.setSelected(true);
            }
            jComboBox1.setSelectedItem(partido);
            jTextArea1.setText(promesas);






        }
    }
    private void jButton1ActionPerformed(java.awt.event. ActionEvent evt)
    {
        String Nombre = jTextField1.getText();
        String Cedula = (String) jComboBox2.getSelectedItem();
        String Ciudad = (String) jComboBox3.getSelectedItem();
        
        String Partido = (String) jComboBox1.getSelectedItem();
        String Promesas = jTextArea1.getText();
        System.out.println(Nombre );
        System.out.println(Cedula);
        System.out.println( Ciudad);
        Boolean Orientacion;
        if(jRadioButton1.isSelected()){
            System.out.println("Selecciono la izquierda");
            Orientacion = false;
        }
        else if(jRadioButton2.isSelected()){
            Orientacion = true;
            System.out.println("Selecciono la derecha");
        }else{
            Orientacion = false;
            System.out.println("El else del final fue el que se ejecuto");
        } 
        System.out.println(Partido);
        String[] arrayDeLineas = Promesas.split("\n");
        System.out.println("Lista de líneas:");
        for (String linea : arrayDeLineas) {
            System.out.println(linea);
        }
        if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false){
            JOptionPane.showMessageDialog(null,"No selecciono ninguna opción de Orientación");
        }
        else{
            if(jTextField1.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor rellena todos los datos (Cedula)", "Error ", JOptionPane.ERROR_MESSAGE); 
                }else{
                    Candidatos candidatonuevo  = new Candidatos(Nombre, Cedula, Ciudad, Orientacion, Partido, Promesas, 0);
                    Principal.Actualizar(candidatonuevo);
                    JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente", "Actualizar Registro ", JOptionPane.INFORMATION_MESSAGE);
                }
        }  
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partido_de_la_U","Partido_Alianza_Verde","Partido_Polo_Democrático_Alternativo", "Colombia_Humana,Partido_Centro_Democrático,Movimiento_Alternativo_Indígena_y_Social","Partido_Colombia_Justa_Libres","Partido_Colombia_Renaciente","Partido_ADA","Partido_Dignidad_y_Compromiso" }));
    }                                             

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partido_Liberal_Colombiano", "Partido_Conservador_Colombiano",
            "Liga_de_Gobernantes_Anticorrupción","Movimiento_Autoridades_Indígenas_de_Colombia",
            "Partido_Verde_Oxígeno", "Unión_Patriótica", "Salvación_Nacional",
            "Partido_Alianza_Social_Independiente","Partido_Cambio_Radical", "Partido_Político_Mira" }));
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroupOrientacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
